### ISSUE TITLE
Remove binaries to reduce repo size

### ISSUE THREAD

**Issue by npyl** [AMarquez94/Atlas-Fate-Between-Light-and-Darkness#7]
Hi!
It would be great if you moved the binaries (take 1GB+ of space) so that cloning and working on the project becomes faster and easier.

Thank you for this game.

**Comment by AMarquez94** [comment]
Hi! First of all, thanks for your interest in the repo and the game :)

By binaries, do you mean the Bin folder? If so, it can't be removed (without making the game unplayable when built) as it contains the game assets, scripts, shaders...

**Comment by npyl** [comment]
Thank you for this info, I now understand.  I meant the Bin folder indeed!
